//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
/// Generated from: lobby.proto

module Cmd {
	/**
	 * ---------------------------------公共定义---------------------------------------//
	 *  用户基本信息-为java对接做好准备
	 */
	// export class UserBaseInfo {
	// 	uid: number;
	// 	headUrl: string;
	// 	nickName: string;
	// 	gender: string;
	// 	chips: number;
	// 	platId: number;
	// 	subPlatId: string;
	// 	/**
	// 	 * 奖券
	// 	 */
	// 	giftCoupon: number;
	// 	/**
	// 	 * 个性签名
	// 	 */
	// 	signature: string;
	// 	GetType(): string { return 'Cmd.UserBaseInfo'; }
	// }
	/**
	 * 庄家配置
	 */
	// export class bankerConfig {
	// 	selectChips: number[];
	// 	lowestBankerChips: number;
	// 	GetType(): string { return 'Cmd.bankerConfig'; }
	// }
	/**
	 * 房间信息
	 */
	// export class RoomInfo {
	// 	/**
	// 	 * 房间id
	// 	 */
	// 	roomId: number;
	// 	/**
	// 	 * 玩家人数上限
	// 	 */
	// 	maxUser: number;
	// 	/**
	// 	 * 房间名称
	// 	 */
	// 	roomName: string;
	// 	/**
	// 	 * 最低携带
	// 	 */
	// 	lowestCarry: number;
	// 	/**
	// 	 * 最低下注
	// 	 */
	// 	lowestBet: number;
	// 	/**
	// 	 * 桌子最多可以坐的人数
	// 	 */
	// 	maxSeat: number;
	// 	/**
	// 	 * 最少申请上庄金币
	// 	 */
	// 	bankerConfig: bankerConfig;
	// 	GetType(): string { return 'Cmd.RoomInfo'; }
	// }
	/**
	 * 充值信息项
	 */
	export class RechargeItem {
		/**
		 * 金额
		 */
		rmb: number;
		glod: number[];
		/**
		 * exchange关系
		 */
		marks: string;
		GetType(): string { return 'Cmd.RechargeItem'; }
	}
	/**
	 * 房间彩金数据
	 */
	export class RoomBonusUserInfo {
		/**
		 * 排名
		 */
		rankIndex: number;
		uid: number;
		/**
		 * 昵称
		 */
		nickName: string;
		/**
		 * 图像
		 */
		headUrl: string;
		/**
		 * 玩家分得才进池
		 */
		bonusChips: number;
		/**
		 * 时间
		 */
		date: string;
		GetType(): string { return 'Cmd.RoomBonusUserInfo'; }
	}
	/**
	 * 用户登陆
	 */
	export class UserInfoSynRequestLobbyCmd_C {
		/**
		 * 密码
		 */
		passwd: string;
		GetType(): string { return 'Cmd.UserInfoSynRequestLobbyCmd_C'; }
	}
	export class UserInfoSynRequestLobbyCmd_S {
		/**
		 * 返回码
		 */
		ret: number;
		/**
		 * 返回信息
		 */
		desc: string;
		/**
		 * 用户ID
		 */
		uid: number;
		/**
		 * 用户基本信息
		 */
		userInfo: UserBaseInfo;
		/**
		 * 房间列表信息
		 */
		roomInfo: RoomInfo[];
		/**
		 * 0表示正常玩家
		 */
		gmLevel: number;
		GetType(): string { return 'Cmd.UserInfoSynRequestLobbyCmd_S'; }
	}
	/**
	 * 用户信息获取
	 */
	export class UserInfoGetLobbyCmd_C {
		/**
		 * 用户ID
		 */
		uid: number;
		GetType(): string { return 'Cmd.UserInfoGetLobbyCmd_C'; }
	}
	export class UserInfoGetLobbyCmd_S {
		/**
		 * 返回码
		 */
		ret: number;
		/**
		 * 用户ID
		 */
		uid: number;
		/**
		 * 用户基本信息
		 */
		userInfo: UserBaseInfo;
		GetType(): string { return 'Cmd.UserInfoGetLobbyCmd_S'; }
	}
	/**
	 * 查询房间彩金数据(暂时不用 预留)
	 */
	export class RoomBonusInfoRequestLobbyCmd_C {
		/**
		 * 0表示最近的领取列表，1表示所有的排名列表
		 */
		reqType: number;
		/**
		 * 查询哪个方间的彩金
		 */
		roomId: number;
		GetType(): string { return 'Cmd.RoomBonusInfoRequestLobbyCmd_C'; }
	}
	export class RoomBonusInfoRequestLobbyCmd_S {
		/**
		 * 返回码
		 */
		ret: number;
		/**
		 * 返回描述
		 */
		desc: string;
		/**
		 * 0表示最近的领取列表，1表示所有的排名列表
		 */
		reqType: number;
		/**
		 * 查询哪个方间的彩金
		 */
		roomId: number;
		/**
		 * 彩金列表
		 */
		userBonusInfo: RoomBonusUserInfo[];
		GetType(): string { return 'Cmd.RoomBonusInfoRequestLobbyCmd_S'; }
	}
}
