//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
/// Generated from: lobby.proto
var __reflect = (this && this.__reflect) || function (p, c, t) {
    p.__class__ = c, t ? t.push(c) : t = [c], p.__types__ = p.__types__ ? t.concat(p.__types__) : t;
};
var Cmd;
(function (Cmd) {
    /**
     * ---------------------------------公共定义---------------------------------------//
     *  用户基本信息-为java对接做好准备
     */
    // export class UserBaseInfo {
    // 	uid: number;
    // 	headUrl: string;
    // 	nickName: string;
    // 	gender: string;
    // 	chips: number;
    // 	platId: number;
    // 	subPlatId: string;
    // 	/**
    // 	 * 奖券
    // 	 */
    // 	giftCoupon: number;
    // 	/**
    // 	 * 个性签名
    // 	 */
    // 	signature: string;
    // 	GetType(): string { return 'Cmd.UserBaseInfo'; }
    // }
    /**
     * 庄家配置
     */
    // export class bankerConfig {
    // 	selectChips: number[];
    // 	lowestBankerChips: number;
    // 	GetType(): string { return 'Cmd.bankerConfig'; }
    // }
    /**
     * 房间信息
     */
    // export class RoomInfo {
    // 	/**
    // 	 * 房间id
    // 	 */
    // 	roomId: number;
    // 	/**
    // 	 * 玩家人数上限
    // 	 */
    // 	maxUser: number;
    // 	/**
    // 	 * 房间名称
    // 	 */
    // 	roomName: string;
    // 	/**
    // 	 * 最低携带
    // 	 */
    // 	lowestCarry: number;
    // 	/**
    // 	 * 最低下注
    // 	 */
    // 	lowestBet: number;
    // 	/**
    // 	 * 桌子最多可以坐的人数
    // 	 */
    // 	maxSeat: number;
    // 	/**
    // 	 * 最少申请上庄金币
    // 	 */
    // 	bankerConfig: bankerConfig;
    // 	GetType(): string { return 'Cmd.RoomInfo'; }
    // }
    /**
     * 充值信息项
     */
    var RechargeItem = (function () {
        function RechargeItem() {
        }
        RechargeItem.prototype.GetType = function () { return 'Cmd.RechargeItem'; };
        return RechargeItem;
    }());
    Cmd.RechargeItem = RechargeItem;
    __reflect(RechargeItem.prototype, "Cmd.RechargeItem");
    /**
     * 房间彩金数据
     */
    var RoomBonusUserInfo = (function () {
        function RoomBonusUserInfo() {
        }
        RoomBonusUserInfo.prototype.GetType = function () { return 'Cmd.RoomBonusUserInfo'; };
        return RoomBonusUserInfo;
    }());
    Cmd.RoomBonusUserInfo = RoomBonusUserInfo;
    __reflect(RoomBonusUserInfo.prototype, "Cmd.RoomBonusUserInfo");
    /**
     * 用户登陆
     */
    var UserInfoSynRequestLobbyCmd_C = (function () {
        function UserInfoSynRequestLobbyCmd_C() {
        }
        UserInfoSynRequestLobbyCmd_C.prototype.GetType = function () { return 'Cmd.UserInfoSynRequestLobbyCmd_C'; };
        return UserInfoSynRequestLobbyCmd_C;
    }());
    Cmd.UserInfoSynRequestLobbyCmd_C = UserInfoSynRequestLobbyCmd_C;
    __reflect(UserInfoSynRequestLobbyCmd_C.prototype, "Cmd.UserInfoSynRequestLobbyCmd_C");
    var UserInfoSynRequestLobbyCmd_S = (function () {
        function UserInfoSynRequestLobbyCmd_S() {
        }
        UserInfoSynRequestLobbyCmd_S.prototype.GetType = function () { return 'Cmd.UserInfoSynRequestLobbyCmd_S'; };
        return UserInfoSynRequestLobbyCmd_S;
    }());
    Cmd.UserInfoSynRequestLobbyCmd_S = UserInfoSynRequestLobbyCmd_S;
    __reflect(UserInfoSynRequestLobbyCmd_S.prototype, "Cmd.UserInfoSynRequestLobbyCmd_S");
    /**
     * 用户信息获取
     */
    var UserInfoGetLobbyCmd_C = (function () {
        function UserInfoGetLobbyCmd_C() {
        }
        UserInfoGetLobbyCmd_C.prototype.GetType = function () { return 'Cmd.UserInfoGetLobbyCmd_C'; };
        return UserInfoGetLobbyCmd_C;
    }());
    Cmd.UserInfoGetLobbyCmd_C = UserInfoGetLobbyCmd_C;
    __reflect(UserInfoGetLobbyCmd_C.prototype, "Cmd.UserInfoGetLobbyCmd_C");
    var UserInfoGetLobbyCmd_S = (function () {
        function UserInfoGetLobbyCmd_S() {
        }
        UserInfoGetLobbyCmd_S.prototype.GetType = function () { return 'Cmd.UserInfoGetLobbyCmd_S'; };
        return UserInfoGetLobbyCmd_S;
    }());
    Cmd.UserInfoGetLobbyCmd_S = UserInfoGetLobbyCmd_S;
    __reflect(UserInfoGetLobbyCmd_S.prototype, "Cmd.UserInfoGetLobbyCmd_S");
    /**
     * 查询房间彩金数据(暂时不用 预留)
     */
    var RoomBonusInfoRequestLobbyCmd_C = (function () {
        function RoomBonusInfoRequestLobbyCmd_C() {
        }
        RoomBonusInfoRequestLobbyCmd_C.prototype.GetType = function () { return 'Cmd.RoomBonusInfoRequestLobbyCmd_C'; };
        return RoomBonusInfoRequestLobbyCmd_C;
    }());
    Cmd.RoomBonusInfoRequestLobbyCmd_C = RoomBonusInfoRequestLobbyCmd_C;
    __reflect(RoomBonusInfoRequestLobbyCmd_C.prototype, "Cmd.RoomBonusInfoRequestLobbyCmd_C");
    var RoomBonusInfoRequestLobbyCmd_S = (function () {
        function RoomBonusInfoRequestLobbyCmd_S() {
        }
        RoomBonusInfoRequestLobbyCmd_S.prototype.GetType = function () { return 'Cmd.RoomBonusInfoRequestLobbyCmd_S'; };
        return RoomBonusInfoRequestLobbyCmd_S;
    }());
    Cmd.RoomBonusInfoRequestLobbyCmd_S = RoomBonusInfoRequestLobbyCmd_S;
    __reflect(RoomBonusInfoRequestLobbyCmd_S.prototype, "Cmd.RoomBonusInfoRequestLobbyCmd_S");
})(Cmd || (Cmd = {}));
