//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
/// Generated from: room.proto
/// <reference path="lobby.ts" />
var __reflect = (this && this.__reflect) || function (p, c, t) {
    p.__class__ = c, t ? t.push(c) : t = [c], p.__types__ = p.__types__ ? t.concat(p.__types__) : t;
};
var Cmd;
(function (Cmd) {
    var Room_Status;
    (function (Room_Status) {
        /**
         * 下注
         */
        Room_Status[Room_Status["GAME_STATUS_BET"] = 1] = "GAME_STATUS_BET";
        /**
         * 开奖
         */
        Room_Status[Room_Status["GAME_STATUS_LTY"] = 2] = "GAME_STATUS_LTY";
    })(Room_Status = Cmd.Room_Status || (Cmd.Room_Status = {}));
    /**
     * 系统开奖信息
     */
    var LotteryInfo = (function () {
        function LotteryInfo() {
        }
        LotteryInfo.prototype.GetType = function () { return 'Cmd.LotteryInfo'; };
        return LotteryInfo;
    }());
    Cmd.LotteryInfo = LotteryInfo;
    __reflect(LotteryInfo.prototype, "Cmd.LotteryInfo");
    var Baseid = (function () {
        function Baseid() {
        }
        Baseid.prototype.GetType = function () { return 'Cmd.Baseid'; };
        return Baseid;
    }());
    Cmd.Baseid = Baseid;
    __reflect(Baseid.prototype, "Cmd.Baseid");
    /**
     * 大小开奖信息
     */
    var SizeInfo = (function () {
        function SizeInfo() {
        }
        SizeInfo.prototype.GetType = function () { return 'Cmd.SizeInfo'; };
        return SizeInfo;
    }());
    Cmd.SizeInfo = SizeInfo;
    __reflect(SizeInfo.prototype, "Cmd.SizeInfo");
    var LotteryNbr = (function () {
        function LotteryNbr() {
        }
        LotteryNbr.prototype.GetType = function () { return 'Cmd.LotteryNbr'; };
        return LotteryNbr;
    }());
    Cmd.LotteryNbr = LotteryNbr;
    __reflect(LotteryNbr.prototype, "Cmd.LotteryNbr");
    /**
     * 所有玩家赢得筹码信息
     */
    var LotteryUser = (function () {
        function LotteryUser() {
        }
        LotteryUser.prototype.GetType = function () { return 'Cmd.LotteryUser'; };
        return LotteryUser;
    }());
    Cmd.LotteryUser = LotteryUser;
    __reflect(LotteryUser.prototype, "Cmd.LotteryUser");
    /**
     * 下注基本信息
     */
    var Betbase = (function () {
        function Betbase() {
        }
        Betbase.prototype.GetType = function () { return 'Cmd.Betbase'; };
        return Betbase;
    }());
    Cmd.Betbase = Betbase;
    __reflect(Betbase.prototype, "Cmd.Betbase");
    /**
     * 特殊奖励信息
     */
    var winbase = (function () {
        function winbase() {
        }
        winbase.prototype.GetType = function () { return 'Cmd.winbase'; };
        return winbase;
    }());
    Cmd.winbase = winbase;
    __reflect(winbase.prototype, "Cmd.winbase");
    /**
     * 房间内玩家基本信息
     */
    var RoomStatusInfo = (function () {
        function RoomStatusInfo() {
        }
        RoomStatusInfo.prototype.GetType = function () { return 'Cmd.RoomStatusInfo'; };
        return RoomStatusInfo;
    }());
    Cmd.RoomStatusInfo = RoomStatusInfo;
    __reflect(RoomStatusInfo.prototype, "Cmd.RoomStatusInfo");
    // export class RoomUserInfo {
    // 	uid: number;
    // 	headurl: string;
    // 	/**
    // 	 * 昵称
    // 	 */
    // 	nickname: string;
    // 	/**
    // 	 * 如果为0就是站着
    // 	 */
    // 	seatid: number;
    // 	/**
    // 	 * 玩家当前筹码
    // 	 */
    // 	remainder: number;
    // 	/**
    // 	 * 玩家本局已下注信息
    // 	 */
    // 	userbet: Betbase[];
    // 	GetType(): string { return 'Cmd.RoomUserInfo'; }
    // }
    /**
     * 下注信息回复
     */
    var BetReturnInfo = (function () {
        function BetReturnInfo() {
        }
        BetReturnInfo.prototype.GetType = function () { return 'Cmd.BetReturnInfo'; };
        return BetReturnInfo;
    }());
    Cmd.BetReturnInfo = BetReturnInfo;
    __reflect(BetReturnInfo.prototype, "Cmd.BetReturnInfo");
    var BankerUserInfo = (function () {
        function BankerUserInfo() {
        }
        BankerUserInfo.prototype.GetType = function () { return 'Cmd.BankerUserInfo'; };
        return BankerUserInfo;
    }());
    Cmd.BankerUserInfo = BankerUserInfo;
    __reflect(BankerUserInfo.prototype, "Cmd.BankerUserInfo");
    /**
     * ---------------------------------消息协议---------------------------------------//
     *  进入游戏
     */
    var RoomEnterRoomCmd_C = (function () {
        function RoomEnterRoomCmd_C() {
        }
        RoomEnterRoomCmd_C.prototype.GetType = function () { return 'Cmd.RoomEnterRoomCmd_C'; };
        return RoomEnterRoomCmd_C;
    }());
    Cmd.RoomEnterRoomCmd_C = RoomEnterRoomCmd_C;
    __reflect(RoomEnterRoomCmd_C.prototype, "Cmd.RoomEnterRoomCmd_C");
    /**
     * 单独回复给玩家
     */
    var RoomEnterRoomCmd_S = (function () {
        function RoomEnterRoomCmd_S() {
        }
        RoomEnterRoomCmd_S.prototype.GetType = function () { return 'Cmd.RoomEnterRoomCmd_S'; };
        return RoomEnterRoomCmd_S;
    }());
    Cmd.RoomEnterRoomCmd_S = RoomEnterRoomCmd_S;
    __reflect(RoomEnterRoomCmd_S.prototype, "Cmd.RoomEnterRoomCmd_S");
    /**
     * 离开游戏
     */
    var RoomLeaveRoomCmd_C = (function () {
        function RoomLeaveRoomCmd_C() {
        }
        RoomLeaveRoomCmd_C.prototype.GetType = function () { return 'Cmd.RoomLeaveRoomCmd_C'; };
        return RoomLeaveRoomCmd_C;
    }());
    Cmd.RoomLeaveRoomCmd_C = RoomLeaveRoomCmd_C;
    __reflect(RoomLeaveRoomCmd_C.prototype, "Cmd.RoomLeaveRoomCmd_C");
    var RoomLeaveRoomCmd_S = (function () {
        function RoomLeaveRoomCmd_S() {
        }
        // deskinfo: Cmd.DeskInfo[];
        RoomLeaveRoomCmd_S.prototype.GetType = function () { return 'Cmd.RoomLeaveRoomCmd_S'; };
        return RoomLeaveRoomCmd_S;
    }());
    Cmd.RoomLeaveRoomCmd_S = RoomLeaveRoomCmd_S;
    __reflect(RoomLeaveRoomCmd_S.prototype, "Cmd.RoomLeaveRoomCmd_S");
    var RoomLeaveRoomCmd_Brd = (function () {
        function RoomLeaveRoomCmd_Brd() {
        }
        // deskinfo: Cmd.DeskInfo;
        RoomLeaveRoomCmd_Brd.prototype.GetType = function () { return 'Cmd.RoomLeaveRoomCmd_Brd'; };
        return RoomLeaveRoomCmd_Brd;
    }());
    Cmd.RoomLeaveRoomCmd_Brd = RoomLeaveRoomCmd_Brd;
    __reflect(RoomLeaveRoomCmd_Brd.prototype, "Cmd.RoomLeaveRoomCmd_Brd");
    /**
     * 下注请求
     */
    var BetRequestRoomCmd_C = (function () {
        function BetRequestRoomCmd_C() {
        }
        BetRequestRoomCmd_C.prototype.GetType = function () { return 'Cmd.BetRequestRoomCmd_C'; };
        return BetRequestRoomCmd_C;
    }());
    Cmd.BetRequestRoomCmd_C = BetRequestRoomCmd_C;
    __reflect(BetRequestRoomCmd_C.prototype, "Cmd.BetRequestRoomCmd_C");
    var BetRequestRoomCmd_S = (function () {
        function BetRequestRoomCmd_S() {
        }
        BetRequestRoomCmd_S.prototype.GetType = function () { return 'Cmd.BetRequestRoomCmd_S'; };
        return BetRequestRoomCmd_S;
    }());
    Cmd.BetRequestRoomCmd_S = BetRequestRoomCmd_S;
    __reflect(BetRequestRoomCmd_S.prototype, "Cmd.BetRequestRoomCmd_S");
    /**
     * 全压和撤销请求
     */
    var AllBetOrRepealRoomCmd_C = (function () {
        function AllBetOrRepealRoomCmd_C() {
        }
        AllBetOrRepealRoomCmd_C.prototype.GetType = function () { return 'Cmd.AllBetOrRepealRoomCmd_C'; };
        return AllBetOrRepealRoomCmd_C;
    }());
    Cmd.AllBetOrRepealRoomCmd_C = AllBetOrRepealRoomCmd_C;
    __reflect(AllBetOrRepealRoomCmd_C.prototype, "Cmd.AllBetOrRepealRoomCmd_C");
    var AllBetOrRepealRoomCmd_S = (function () {
        function AllBetOrRepealRoomCmd_S() {
        }
        AllBetOrRepealRoomCmd_S.prototype.GetType = function () { return 'Cmd.AllBetOrRepealRoomCmd_S'; };
        return AllBetOrRepealRoomCmd_S;
    }());
    Cmd.AllBetOrRepealRoomCmd_S = AllBetOrRepealRoomCmd_S;
    __reflect(AllBetOrRepealRoomCmd_S.prototype, "Cmd.AllBetOrRepealRoomCmd_S");
    /**
     * 开始游戏
     */
    var StartGameRoomCmd_C = (function () {
        function StartGameRoomCmd_C() {
        }
        StartGameRoomCmd_C.prototype.GetType = function () { return 'Cmd.StartGameRoomCmd_C'; };
        return StartGameRoomCmd_C;
    }());
    Cmd.StartGameRoomCmd_C = StartGameRoomCmd_C;
    __reflect(StartGameRoomCmd_C.prototype, "Cmd.StartGameRoomCmd_C");
    var StartGameRoomCmd_S = (function () {
        function StartGameRoomCmd_S() {
        }
        StartGameRoomCmd_S.prototype.GetType = function () { return 'Cmd.StartGameRoomCmd_S'; };
        return StartGameRoomCmd_S;
    }());
    Cmd.StartGameRoomCmd_S = StartGameRoomCmd_S;
    __reflect(StartGameRoomCmd_S.prototype, "Cmd.StartGameRoomCmd_S");
    /**
     * 压大小
     */
    var BetSizeRoomCmd_C = (function () {
        function BetSizeRoomCmd_C() {
        }
        BetSizeRoomCmd_C.prototype.GetType = function () { return 'Cmd.BetSizeRoomCmd_C'; };
        return BetSizeRoomCmd_C;
    }());
    Cmd.BetSizeRoomCmd_C = BetSizeRoomCmd_C;
    __reflect(BetSizeRoomCmd_C.prototype, "Cmd.BetSizeRoomCmd_C");
    var BetSizeRoomCmd_S = (function () {
        function BetSizeRoomCmd_S() {
        }
        BetSizeRoomCmd_S.prototype.GetType = function () { return 'Cmd.BetSizeRoomCmd_S'; };
        return BetSizeRoomCmd_S;
    }());
    Cmd.BetSizeRoomCmd_S = BetSizeRoomCmd_S;
    __reflect(BetSizeRoomCmd_S.prototype, "Cmd.BetSizeRoomCmd_S");
    /**
     * 金币转换
     */
    var TrueGoldRoomCmd_C = (function () {
        function TrueGoldRoomCmd_C() {
        }
        TrueGoldRoomCmd_C.prototype.GetType = function () { return 'Cmd.TrueGoldRoomCmd_C'; };
        return TrueGoldRoomCmd_C;
    }());
    Cmd.TrueGoldRoomCmd_C = TrueGoldRoomCmd_C;
    __reflect(TrueGoldRoomCmd_C.prototype, "Cmd.TrueGoldRoomCmd_C");
    var TrueGoldRoomCmd_S = (function () {
        function TrueGoldRoomCmd_S() {
        }
        TrueGoldRoomCmd_S.prototype.GetType = function () { return 'Cmd.TrueGoldRoomCmd_S'; };
        return TrueGoldRoomCmd_S;
    }());
    Cmd.TrueGoldRoomCmd_S = TrueGoldRoomCmd_S;
    __reflect(TrueGoldRoomCmd_S.prototype, "Cmd.TrueGoldRoomCmd_S");
    /**
     * 开奖广播
     */
    var LotteryRoomCmd_Brd = (function () {
        function LotteryRoomCmd_Brd() {
        }
        LotteryRoomCmd_Brd.prototype.GetType = function () { return 'Cmd.LotteryRoomCmd_Brd'; };
        return LotteryRoomCmd_Brd;
    }());
    Cmd.LotteryRoomCmd_Brd = LotteryRoomCmd_Brd;
    __reflect(LotteryRoomCmd_Brd.prototype, "Cmd.LotteryRoomCmd_Brd");
    /**
     * 下注广播
     */
    var BetBeginRoomCmd_Brd = (function () {
        function BetBeginRoomCmd_Brd() {
        }
        BetBeginRoomCmd_Brd.prototype.GetType = function () { return 'Cmd.BetBeginRoomCmd_Brd'; };
        return BetBeginRoomCmd_Brd;
    }());
    Cmd.BetBeginRoomCmd_Brd = BetBeginRoomCmd_Brd;
    __reflect(BetBeginRoomCmd_Brd.prototype, "Cmd.BetBeginRoomCmd_Brd");
})(Cmd || (Cmd = {}));
