//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
/// Generated from: room.proto
var __reflect = (this && this.__reflect) || function (p, c, t) {
    p.__class__ = c, t ? t.push(c) : t = [c], p.__types__ = p.__types__ ? t.concat(p.__types__) : t;
};
var Cmd;
(function (Cmd) {
    /**
     * 玩家基本信息，用于显示头像
     */
    var UserBriefInfo = (function () {
        function UserBriefInfo() {
        }
        UserBriefInfo.prototype.GetType = function () { return 'Cmd.UserBriefInfo'; };
        return UserBriefInfo;
    }());
    Cmd.UserBriefInfo = UserBriefInfo;
    __reflect(UserBriefInfo.prototype, "Cmd.UserBriefInfo");
    /**
     * 进入游戏
     */
    var EnterGameCmd_C = (function () {
        function EnterGameCmd_C() {
        }
        EnterGameCmd_C.prototype.GetType = function () { return 'Cmd.EnterGameCmd_C'; };
        return EnterGameCmd_C;
    }());
    Cmd.EnterGameCmd_C = EnterGameCmd_C;
    __reflect(EnterGameCmd_C.prototype, "Cmd.EnterGameCmd_C");
    var EnterGameCmd_S = (function () {
        function EnterGameCmd_S() {
        }
        EnterGameCmd_S.prototype.GetType = function () { return 'Cmd.EnterGameCmd_S'; };
        return EnterGameCmd_S;
    }());
    Cmd.EnterGameCmd_S = EnterGameCmd_S;
    __reflect(EnterGameCmd_S.prototype, "Cmd.EnterGameCmd_S");
    /**
     * 游戏信息
     */
    var GameInfo = (function () {
        function GameInfo() {
        }
        GameInfo.prototype.GetType = function () { return 'Cmd.GameInfo'; };
        return GameInfo;
    }());
    Cmd.GameInfo = GameInfo;
    __reflect(GameInfo.prototype, "Cmd.GameInfo");
    /**
     * 轮子
     */
    var WhellItem = (function () {
        function WhellItem() {
        }
        WhellItem.prototype.GetType = function () { return 'Cmd.WhellItem'; };
        return WhellItem;
    }());
    Cmd.WhellItem = WhellItem;
    __reflect(WhellItem.prototype, "Cmd.WhellItem");
    /**
     * 退出游戏
     */
    var ExitGameCmd_C = (function () {
        function ExitGameCmd_C() {
        }
        ExitGameCmd_C.prototype.GetType = function () { return 'Cmd.ExitGameCmd_C'; };
        return ExitGameCmd_C;
    }());
    Cmd.ExitGameCmd_C = ExitGameCmd_C;
    __reflect(ExitGameCmd_C.prototype, "Cmd.ExitGameCmd_C");
    var ExitGameCmd_S = (function () {
        function ExitGameCmd_S() {
        }
        ExitGameCmd_S.prototype.GetType = function () { return 'Cmd.ExitGameCmd_S'; };
        return ExitGameCmd_S;
    }());
    Cmd.ExitGameCmd_S = ExitGameCmd_S;
    __reflect(ExitGameCmd_S.prototype, "Cmd.ExitGameCmd_S");
    /**
     * 改变旋转速度
     */
    var SetSpeedCmd_C = (function () {
        function SetSpeedCmd_C() {
        }
        SetSpeedCmd_C.prototype.GetType = function () { return 'Cmd.SetSpeedCmd_C'; };
        return SetSpeedCmd_C;
    }());
    Cmd.SetSpeedCmd_C = SetSpeedCmd_C;
    __reflect(SetSpeedCmd_C.prototype, "Cmd.SetSpeedCmd_C");
    var SetSpeedCmd_S = (function () {
        function SetSpeedCmd_S() {
        }
        SetSpeedCmd_S.prototype.GetType = function () { return 'Cmd.SetSpeedCmd_S'; };
        return SetSpeedCmd_S;
    }());
    Cmd.SetSpeedCmd_S = SetSpeedCmd_S;
    __reflect(SetSpeedCmd_S.prototype, "Cmd.SetSpeedCmd_S");
    /**
     * 下注
     */
    var BetRequestCmd_C = (function () {
        function BetRequestCmd_C() {
        }
        BetRequestCmd_C.prototype.GetType = function () { return 'Cmd.BetRequestCmd_C'; };
        return BetRequestCmd_C;
    }());
    Cmd.BetRequestCmd_C = BetRequestCmd_C;
    __reflect(BetRequestCmd_C.prototype, "Cmd.BetRequestCmd_C");
    var BetRequestCmd_S = (function () {
        function BetRequestCmd_S() {
        }
        BetRequestCmd_S.prototype.GetType = function () { return 'Cmd.BetRequestCmd_S'; };
        return BetRequestCmd_S;
    }());
    Cmd.BetRequestCmd_S = BetRequestCmd_S;
    __reflect(BetRequestCmd_S.prototype, "Cmd.BetRequestCmd_S");
    var CancelAutoBetCmd_C = (function () {
        function CancelAutoBetCmd_C() {
        }
        CancelAutoBetCmd_C.prototype.GetType = function () { return 'Cmd.CancelAutoBetCmd_C'; };
        return CancelAutoBetCmd_C;
    }());
    Cmd.CancelAutoBetCmd_C = CancelAutoBetCmd_C;
    __reflect(CancelAutoBetCmd_C.prototype, "Cmd.CancelAutoBetCmd_C");
    var CancelAutoBetCmd_S = (function () {
        function CancelAutoBetCmd_S() {
        }
        CancelAutoBetCmd_S.prototype.GetType = function () { return 'Cmd.CancelAutoBetCmd_S'; };
        return CancelAutoBetCmd_S;
    }());
    Cmd.CancelAutoBetCmd_S = CancelAutoBetCmd_S;
    __reflect(CancelAutoBetCmd_S.prototype, "Cmd.CancelAutoBetCmd_S");
    /**
     * 转轮结果
     */
    var WhellResultCmd_S = (function () {
        function WhellResultCmd_S() {
        }
        WhellResultCmd_S.prototype.GetType = function () { return 'Cmd.WhellResultCmd_S'; };
        return WhellResultCmd_S;
    }());
    Cmd.WhellResultCmd_S = WhellResultCmd_S;
    __reflect(WhellResultCmd_S.prototype, "Cmd.WhellResultCmd_S");
    /**
     * 开奖
     */
    var LotteryCmd_S = (function () {
        function LotteryCmd_S() {
        }
        LotteryCmd_S.prototype.GetType = function () { return 'Cmd.LotteryCmd_S'; };
        return LotteryCmd_S;
    }());
    Cmd.LotteryCmd_S = LotteryCmd_S;
    __reflect(LotteryCmd_S.prototype, "Cmd.LotteryCmd_S");
    /**
     * 开奖元素
     */
    var LotteryItem = (function () {
        function LotteryItem() {
        }
        LotteryItem.prototype.GetType = function () { return 'Cmd.LotteryItem'; };
        return LotteryItem;
    }());
    Cmd.LotteryItem = LotteryItem;
    __reflect(LotteryItem.prototype, "Cmd.LotteryItem");
    /**
     * 特殊奖励
     */
    var SpecLotCmd_S = (function () {
        function SpecLotCmd_S() {
        }
        SpecLotCmd_S.prototype.GetType = function () { return 'Cmd.SpecLotCmd_S'; };
        return SpecLotCmd_S;
    }());
    Cmd.SpecLotCmd_S = SpecLotCmd_S;
    __reflect(SpecLotCmd_S.prototype, "Cmd.SpecLotCmd_S");
    /**
     * 选取宝箱
     */
    var PickSpecLotCmd_C = (function () {
        function PickSpecLotCmd_C() {
        }
        PickSpecLotCmd_C.prototype.GetType = function () { return 'Cmd.PickSpecLotCmd_C'; };
        return PickSpecLotCmd_C;
    }());
    Cmd.PickSpecLotCmd_C = PickSpecLotCmd_C;
    __reflect(PickSpecLotCmd_C.prototype, "Cmd.PickSpecLotCmd_C");
    var PickSpecLotCmd_S = (function () {
        function PickSpecLotCmd_S() {
        }
        PickSpecLotCmd_S.prototype.GetType = function () { return 'Cmd.PickSpecLotCmd_S'; };
        return PickSpecLotCmd_S;
    }());
    Cmd.PickSpecLotCmd_S = PickSpecLotCmd_S;
    __reflect(PickSpecLotCmd_S.prototype, "Cmd.PickSpecLotCmd_S");
    /**
     * 进入免费游戏
     */
    var FreeGameCmd_S = (function () {
        function FreeGameCmd_S() {
        }
        FreeGameCmd_S.prototype.GetType = function () { return 'Cmd.FreeGameCmd_S'; };
        return FreeGameCmd_S;
    }());
    Cmd.FreeGameCmd_S = FreeGameCmd_S;
    __reflect(FreeGameCmd_S.prototype, "Cmd.FreeGameCmd_S");
})(Cmd || (Cmd = {}));
